//
// EventsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class EventsAPI: APIBase {
    /**
     Creates a single event (a transaction with no duration)
     
     - parameter customerId: (query) customerId 
     - parameter request: (body) Similar to transactions, the details of that event (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createEvent(customerId: String, request: NewEventRequest? = nil, completion: @escaping ((_ error: Error?) -> Void)) {
        createEventWithRequestBuilder(customerId: customerId, request: request).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Creates a single event (a transaction with no duration)
     - POST /v2/events
     
     - parameter customerId: (query) customerId 
     - parameter request: (body) Similar to transactions, the details of that event (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func createEventWithRequestBuilder(customerId: String, request: NewEventRequest? = nil) -> RequestBuilder<Void> {
        let path = "/v2/events"
        let URLString = DataCollectorAPI.basePath + path
        let parameters = request?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "customerId": customerId
        ])
        

        let requestBuilder: RequestBuilder<Void>.Type = DataCollectorAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
