//
// BatchRequestResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class BatchRequestResult: JSONEncodable {

    /** HTTP response code for the processed request */
    public var code: Int32?
    /** Error messages if the request could not be processed */
    public var errors: [String]?
    /** The request. Will be null if request was successfully processed */
    public var request: DataCollectorBaseRequest?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["code"] = self.code?.encodeToJSON()
        nillableDictionary["errors"] = self.errors?.encodeToJSON()
        nillableDictionary["request"] = self.request?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
