//
// DataCollectorUpdateCollectionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class DataCollectorUpdateCollectionRequest: DataCollectorBaseRequest {

    /** Final balance after the transaction */
    public var balance: Double?
    /** The amount changed (delta) in the transaction */
    public var balanceModification: Double?
    /** Whether the unit being updated is a currency unit or not */
    public var currency: Bool?
    /** Name of the unit/collection/currency being updated */
    public var name: String?

    

    // MARK: JSONEncodable
    override open func encodeToJSON() -> Any {
        var nillableDictionary = super.encodeToJSON() as? [String:Any?] ?? [String:Any?]()
        nillableDictionary["balance"] = self.balance
        nillableDictionary["balance_modification"] = self.balanceModification
        nillableDictionary["currency"] = self.currency
        nillableDictionary["name"] = self.name

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
