//
// BatchAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class BatchAPI: APIBase {
    /**
     Submit a batch of requests as an array of input models
     
     - parameter batchRequest: (body) batchRequest 
     - parameter customerId: (query) customerId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func batchUsingPOST(batchRequest: DataCollectorBatchRequest, customerId: String, completion: @escaping ((_ error: Error?) -> Void)) {
        batchUsingPOSTWithRequestBuilder(batchRequest: batchRequest, customerId: customerId).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Submit a batch of requests as an array of input models
     - POST /v2/batch
     - For this to work, you will need to specify the value of the request_type field of each element in the list, which indicates the type of the element. For example, to submit a batch containing a DataCollectorNewUserRequest you would specify the value `newUser` as the request_type for your DataCollectorNewUserRequest element. Convention is DataCollectorSomeTypeRequest -> someType (DataCollectorNewUserRequest -> newUser, DataCollectorNewDeviceRequest -> newDevice, etc
     
     - parameter batchRequest: (body) batchRequest 
     - parameter customerId: (query) customerId 

     - returns: RequestBuilder<Void> 
     */
    open class func batchUsingPOSTWithRequestBuilder(batchRequest: DataCollectorBatchRequest, customerId: String) -> RequestBuilder<Void> {
        let path = "/v2/batch"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = batchRequest.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "customerId": customerId
        ])
        

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
